version: 2.1 # use CircleCI 2.1
orbs:
    telegram_entry: woltsu/telegram@0.0.9
    telegram: uniqueck/telegram-orb@0.0.1

jobs:
  build:
    docker: # run the steps with Docker
          - image: circleci/openjdk:11-jdk-stretch 

    #working_directory: ~/AccountSystem

    steps:
 
     # git pull
      - checkout

      - telegram_entry/notify:
          message: "[CircleCI]: starting CI commit ${CIRCLE_SHA1} by ${CIRCLE_USERNAME}"
          #          telegram-chat-id: TELEGRAM_CHAT_ID
          #telegram-bot-token: TELEGRAM_BOT_TOKEN
           
      # Download and cache dependencies
      - restore_cache:
          keys:
          - sample-springboot-api-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: sample-springboot-api-{{ checksum "pom.xml" }}
        
      # package into a jar
      - run: mvn clean package 
      
      - run: 
            name: Login to Dockerhub
            command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
            name: push image to Dockerhub
            command: mvn clean compile jib:build -Dimage=mateusmsouza4/antenas-project:$CIRCLE_BUILD_NUM

      # store raw contents of src code
      - store_artifacts:
          path: target/classes
          destination: sample-springboot-api
      - telegram/status

workflows:
  version: 2
  build:
      jobs:
         - build:
            context: ANTENA
            filters:
              branches:
                only:
                  - master

