version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
        - image: circleci/openjdk:8-jdk-stretch 
        - image: circleci/mysql:latest

    working_directory: ~/AccountSystem

    steps:
      # git pull
      - checkout

      # setup testing env
      - setup_remote_docker:
          docker_layer_caching: true
          #- run:
          #name: Login to DockerHub
          #command: docker login -u $DOCKER_USER -p $DOCKER_PASS
          #- run:
          #name: Decrpyt Secrets
          #command: openssl enc -d -aes-256-ecb -md md5 -in src/main/resources/application-prod.properties.secrets -out src/main/resources/application-prod.properties -k $SECRETS_KEY
            
      # Download and cache dependencies
      - restore_cache:
          keys:
          - sample-springboot-api-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: sample-springboot-api-{{ checksum "pom.xml" }}
        
      # package into a jar
      - run: mvn clean package

      # store raw contents of src code
      - store_artifacts:
          path: target/classes
          destination: sample-springboot-api
workflows:
  version: 2
  build:
      jobs:
          - build

