version: 2.1 # use CircleCI 2.1
orbs:
        #telegram: woltsu/telegram@0.0.9
    telegram: iuniqueck/telegram-orb@0.0.1

jobs:
  build:
    docker: # run the steps with Docker
          - image: circleci/openjdk:8-jdk-stretch 

    #working_directory: ~/AccountSystem

    steps:
      # git pull
      - checkout
            
      # Download and cache dependencies
      - restore_cache:
          keys:
          - sample-springboot-api-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: sample-springboot-api-{{ checksum "pom.xml" }}
        
      # package into a jar
      - run: mvn clean package 

      # store raw contents of src code
      - store_artifacts:
          path: target/classes
          destination: sample-springboot-api
      - telegram/status
          #- telegram/notify:
          #context: ANTENA
          #message: "[CircleCI]: reporting CI result: "
          #telegram-chat-id: TELEGRAM_CHAT_ID
          #telegram-bot-token: TELEGRAM_BOT_TOKEN

workflows:
  version: 2
  build:
      jobs:
              #- telegram/notify:
              #context: ANTENA
              #message: "[CircleCI]: starting CI commit ${CIRCLE_SHA1} by ${CIRCLE_USERNAME}"
              #telegram-chat-id: TELEGRAM_CHAT_ID
              #telegram-bot-token: TELEGRAM_BOT_TOKEN

         - build:
                 #requires:
                 #- telegram/notify
            context: ANTENA
            filters:
              branches:
                only:
                  - master

