version: 2.1

orbs:
    telegram_entry: woltsu/telegram@0.0.9
    telegram: uniqueck/telegram-orb@0.0.1
    sonarcloud: sonarsource/sonarcloud@1.0.1

    jobs:
      build:
        docker:
          - image: 'circleci/openjdk:11-jdk'
        steps:
          - checkout
          - run:
              name: Analyze on SonarCloud
              command: mvn verify sonar:sonar
    
    workflows:
      main:
        jobs:
          - build:
              context: AntenasService